# frozen_string_literal: true

module Engine
  module Game
    module G1872
      module Entities
        COMPANIES = [
          {
            name: 'Kyoto Railway Co.',
            value: 20,
            revenue: 5,
            desc: 'No special ability. Blocks hex D10 while owned by a player.',
            sym: 'KT',
            # abilities: [{ type: 'blocks_hexes', owner_type: 'player', hexes: ['D8'] }],
            color: nil,
          },
        ].freeze

        CORPORATIONS = [
          {
            float_percent: 60,
            sym: 'SMB',
            name: "Shimabara Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'A45',
            color: '#fe2',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'KRC',
            name: "Kyushu Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'C41',
            color: '#f77',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'IYO',
            name: "Iyo Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'H40',
            color: '#ec9',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'TKS',
            name: "Tokushima Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'L38',
            color: '#e93',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'SRC',
            name: "San'yo Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'N36',
            color: '#ddd',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'KYO',
            name: "Kyoto Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'O35',
            color: '#070',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'KAN',
            name: "Kansai Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'O37',
            city: 1,
            color: '#22c',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'NAG',
            name: "Nagoya Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'R32',
            color: '#5ad',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'NAN',
            name: "Nanao Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'R26',
            color: '#e9e',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'SHI',
            name: "Shinano Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'U25',
            color: '#369',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'JGR',
            name: "Japanese Government Railway",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0],
            coordinates: 'X32',
            color: '#e00',
            text_color: 'white',
            reservation_color: nil,
          },
          # {
          #   float_percent: 60,
          #   sym: 'HER',
          #   name: "Hiroshima Electric Railway",
          #   logo: '18_tokaido/SRC',
          #   simple_logo: '18_tokaido/SRC.alt',
          #   tokens: [0, 40, 60],
          #   coordinates: 'G37',
          #   color: '#ef8f2f',
          #   text_color: 'black',
          #   reservation_color: nil,
          # },
          {
            float_percent: 60,
            sym: 'NRC',
            name: "Nippon Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'Y31',
            city: 1,
            color: '#000',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'TOB',
            name: "Tobu Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'Y31',
            city: 1,
            color: '#777',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'SOB',
            name: "Sobu Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'Y31',
            city: 2,
            color: '#cc0',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'ECH',
            name: "Echigo Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'W19',
            color: '#9d9',
            text_color: 'black',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'GAN',
            name: "Ganetsu Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'AA21',
            color: '#939',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'HCR',
            name: "Hokkaido Colliery and Railway",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'I13',
            color: '#963',
            text_color: 'white',
            reservation_color: nil,
          },
          {
            float_percent: 60,
            sym: 'HOR',
            name: "Horonai Railway Co.",
            logo: '18_tokaido/SRC',
            simple_logo: '18_tokaido/SRC.alt',
            tokens: [0, 40, 60],
            coordinates: 'I17',
            color: '#3bb',
            text_color: 'black',
            reservation_color: nil,
          },
        ].freeze
      end
    end
  end
end
